# general settings
name: train_animesr_step2_lbo_1_net
model_type: DegradationModel
scale: 2
num_gpu: auto  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: LBO_1
    type: CustomPairedImageDataset
    dataroot_gt: results/input_rescaling_strategy_lbo_1/frames  # TO_MODIFY
    dataroot_lq: datasets/lbo_training_data/real_world_video_to_train_lbo_1  # TO_MODIFY
    io_backend:
      type: disk

    gt_size: 256
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 12
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 200
    prefetch_mode: ~

# network structures
network_g:
  type: SimpleDegradationArch
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  downscale: 2


# path
path:
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [50000]
    gamma: 0.5

  total_iter: 100000
  warmup_iter: -1  # no warm up

  # losses
  l1_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  l2_opt:
    type: MSELoss
    loss_weight: 1.0
    reduction: mean

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
