# general settings
name: train_animesr_step1_net_BasicOPonly
model_type: VideoRecurrentCustomModel
scale: 4
num_gpu: auto  # set num_gpu: 0 for cpu mode
manual_seed: 0

# USM the ground-truth
l1_gt_usm: True

# dataset and data loader settings
datasets:
  train:
    name: AVC-Train
    type: FFMPEGAnimeDataset
    dataroot_gt: datasets/AVC-Train  # TO_MODIFY
    test_mode: False
    io_backend:
      type: disk

    num_frame: 15
    gt_size: 256
    interval_list: [1, 2, 3]
    random_reverse: True
    use_flip: true
    use_rot: true
    usm_sharp_gt: True
    usm_weight: 0.3
    usm_radius: 50

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 20
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~
    pin_memory: True

# network structures
network_g:
  type: MSRSWVSR
  num_feat: 64
  num_block: [5, 3, 2]

# path
path:
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [300000]
    gamma: 0.5

  total_iter: 300000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
#val:
#  val_freq: !!float 1e4
#  save_img: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true
